package org.snowprojects.module.materialcolors

import android.content.Context
import androidx.annotation.ColorInt
import androidx.core.content.ContextCompat

/**
 * Created by Snow Corp Team on 17/08/20 at 9:38 AM.
 * support@snowcorp.org
 * www.snowcorp.org
 */

class Colors(private val context: Context) {
    private fun getColor(resId: Int): Int {
        return ContextCompat.getColor(context, resId)
    }

    @ColorInt val red_50 = getColor(R.color.red_50)
    @ColorInt val red_100 = getColor(R.color.red_100)
    @ColorInt val red_200 = getColor(R.color.red_200)
    @ColorInt val red_300 = getColor(R.color.red_300)
    @ColorInt val red_400 = getColor(R.color.red_400)
    @ColorInt val red_500 = getColor(R.color.red_500)
    @ColorInt val red_600 = getColor(R.color.red_600)
    @ColorInt val red_700 = getColor(R.color.red_700)
    @ColorInt val red_800 = getColor(R.color.red_800)
    @ColorInt val red_900 = getColor(R.color.red_900)
    @ColorInt val red_a100 = getColor(R.color.red_a100)
    @ColorInt val red_a200 = getColor(R.color.red_a200)
    @ColorInt val red_a400 = getColor(R.color.red_a400)
    @ColorInt val red_a700 = getColor(R.color.red_a700)

    @ColorInt val pink_50 = getColor(R.color.pink_50)
    @ColorInt val pink_100 = getColor(R.color.pink_100)
    @ColorInt val pink_200 = getColor(R.color.pink_200)
    @ColorInt val pink_300 = getColor(R.color.pink_300)
    @ColorInt val pink_400 = getColor(R.color.pink_400)
    @ColorInt val pink_500 = getColor(R.color.pink_500)
    @ColorInt val pink_600 = getColor(R.color.pink_600)
    @ColorInt val pink_700 = getColor(R.color.pink_700)
    @ColorInt val pink_800 = getColor(R.color.pink_800)
    @ColorInt val pink_900 = getColor(R.color.pink_900)
    @ColorInt val pink_a100 = getColor(R.color.pink_a100)
    @ColorInt val pink_a200 = getColor(R.color.pink_a200)
    @ColorInt val pink_a400 = getColor(R.color.pink_a400)
    @ColorInt val pink_a700 = getColor(R.color.pink_a700)

    @ColorInt val purple_50 = getColor(R.color.purple_50)
    @ColorInt val purple_100 = getColor(R.color.purple_100)
    @ColorInt val purple_200 = getColor(R.color.purple_200)
    @ColorInt val purple_300 = getColor(R.color.purple_300)
    @ColorInt val purple_400 = getColor(R.color.purple_400)
    @ColorInt val purple_500 = getColor(R.color.purple_500)
    @ColorInt val purple_600 = getColor(R.color.purple_600)
    @ColorInt val purple_700 = getColor(R.color.purple_700)
    @ColorInt val purple_800 = getColor(R.color.purple_800)
    @ColorInt val purple_900 = getColor(R.color.purple_900)
    @ColorInt val purple_a100 = getColor(R.color.purple_a100)
    @ColorInt val purple_a200 = getColor(R.color.purple_a200)
    @ColorInt val purple_a400 = getColor(R.color.purple_a400)
    @ColorInt val purple_a700 = getColor(R.color.purple_a700)

    @ColorInt val deep_purple_50 = getColor(R.color.deep_purple_50)
    @ColorInt val deep_purple_100 = getColor(R.color.deep_purple_100)
    @ColorInt val deep_purple_200 = getColor(R.color.deep_purple_200)
    @ColorInt val deep_purple_300 = getColor(R.color.deep_purple_300)
    @ColorInt val deep_purple_400 = getColor(R.color.deep_purple_400)
    @ColorInt val deep_purple_500 = getColor(R.color.deep_purple_500)
    @ColorInt val deep_purple_600 = getColor(R.color.deep_purple_600)
    @ColorInt val deep_purple_700 = getColor(R.color.deep_purple_700)
    @ColorInt val deep_purple_800 = getColor(R.color.deep_purple_800)
    @ColorInt val deep_purple_900 = getColor(R.color.deep_purple_900)
    @ColorInt val deep_purple_a100 = getColor(R.color.deep_purple_a100)
    @ColorInt val deep_purple_a200 = getColor(R.color.deep_purple_a200)
    @ColorInt val deep_purple_a400 = getColor(R.color.deep_purple_a400)
    @ColorInt val deep_purple_a700 = getColor(R.color.deep_purple_a700)

    @ColorInt val indigo_50 = getColor(R.color.indigo_50)
    @ColorInt val indigo_100 = getColor(R.color.indigo_100)
    @ColorInt val indigo_200 = getColor(R.color.indigo_200)
    @ColorInt val indigo_300 = getColor(R.color.indigo_300)
    @ColorInt val indigo_400 = getColor(R.color.indigo_400)
    @ColorInt val indigo_500 = getColor(R.color.indigo_500)
    @ColorInt val indigo_600 = getColor(R.color.indigo_600)
    @ColorInt val indigo_700 = getColor(R.color.indigo_700)
    @ColorInt val indigo_800 = getColor(R.color.indigo_800)
    @ColorInt val indigo_900 = getColor(R.color.indigo_900)
    @ColorInt val indigo_a100 = getColor(R.color.indigo_a100)
    @ColorInt val indigo_a200 = getColor(R.color.indigo_a200)
    @ColorInt val indigo_a400 = getColor(R.color.indigo_a400)
    @ColorInt val indigo_a700 = getColor(R.color.indigo_a700)

    @ColorInt val blue_50 = getColor(R.color.blue_50)
    @ColorInt val blue_100 = getColor(R.color.blue_100)
    @ColorInt val blue_200 = getColor(R.color.blue_200)
    @ColorInt val blue_300 = getColor(R.color.blue_300)
    @ColorInt val blue_400 = getColor(R.color.blue_400)
    @ColorInt val blue_500 = getColor(R.color.blue_500)
    @ColorInt val blue_600 = getColor(R.color.blue_600)
    @ColorInt val blue_700 = getColor(R.color.blue_700)
    @ColorInt val blue_800 = getColor(R.color.blue_800)
    @ColorInt val blue_900 = getColor(R.color.blue_900)
    @ColorInt val blue_a100 = getColor(R.color.blue_a100)
    @ColorInt val blue_a200 = getColor(R.color.blue_a200)
    @ColorInt val blue_a400 = getColor(R.color.blue_a400)
    @ColorInt val blue_a700 = getColor(R.color.blue_a700)

    @ColorInt val light_blue_50 = getColor(R.color.light_blue_50)
    @ColorInt val light_blue_100 = getColor(R.color.light_blue_100)
    @ColorInt val light_blue_200 = getColor(R.color.light_blue_200)
    @ColorInt val light_blue_300 = getColor(R.color.light_blue_300)
    @ColorInt val light_blue_400 = getColor(R.color.light_blue_400)
    @ColorInt val light_blue_500 = getColor(R.color.light_blue_500)
    @ColorInt val light_blue_600 = getColor(R.color.light_blue_600)
    @ColorInt val light_blue_700 = getColor(R.color.light_blue_700)
    @ColorInt val light_blue_800 = getColor(R.color.light_blue_800)
    @ColorInt val light_blue_900 = getColor(R.color.light_blue_900)
    @ColorInt val light_blue_a100 = getColor(R.color.light_blue_a100)
    @ColorInt val light_blue_a200 = getColor(R.color.light_blue_a200)
    @ColorInt val light_blue_a400 = getColor(R.color.light_blue_a400)
    @ColorInt val light_blue_a700 = getColor(R.color.light_blue_a700)

    @ColorInt val cyan_50 = getColor(R.color.cyan_50)
    @ColorInt val cyan_100 = getColor(R.color.cyan_100)
    @ColorInt val cyan_200 = getColor(R.color.cyan_200)
    @ColorInt val cyan_300 = getColor(R.color.cyan_300)
    @ColorInt val cyan_400 = getColor(R.color.cyan_400)
    @ColorInt val cyan_500 = getColor(R.color.cyan_500)
    @ColorInt val cyan_600 = getColor(R.color.cyan_600)
    @ColorInt val cyan_700 = getColor(R.color.cyan_700)
    @ColorInt val cyan_800 = getColor(R.color.cyan_800)
    @ColorInt val cyan_900 = getColor(R.color.cyan_900)
    @ColorInt val cyan_a100 = getColor(R.color.cyan_a100)
    @ColorInt val cyan_a200 = getColor(R.color.cyan_a200)
    @ColorInt val cyan_a400 = getColor(R.color.cyan_a400)
    @ColorInt val cyan_a700 = getColor(R.color.cyan_a700)

    @ColorInt val teal_50 = getColor(R.color.teal_50)
    @ColorInt val teal_100 = getColor(R.color.teal_100)
    @ColorInt val teal_200 = getColor(R.color.teal_200)
    @ColorInt val teal_300 = getColor(R.color.teal_300)
    @ColorInt val teal_400 = getColor(R.color.teal_400)
    @ColorInt val teal_500 = getColor(R.color.teal_500)
    @ColorInt val teal_600 = getColor(R.color.teal_600)
    @ColorInt val teal_700 = getColor(R.color.teal_700)
    @ColorInt val teal_800 = getColor(R.color.teal_800)
    @ColorInt val teal_900 = getColor(R.color.teal_900)
    @ColorInt val teal_a100 = getColor(R.color.teal_a100)
    @ColorInt val teal_a200 = getColor(R.color.teal_a200)
    @ColorInt val teal_a400 = getColor(R.color.teal_a400)
    @ColorInt val teal_a700 = getColor(R.color.teal_a700)

    @ColorInt val green_50 = getColor(R.color.green_50)
    @ColorInt val green_100 = getColor(R.color.green_100)
    @ColorInt val green_200 = getColor(R.color.green_200)
    @ColorInt val green_300 = getColor(R.color.green_300)
    @ColorInt val green_400 = getColor(R.color.green_400)
    @ColorInt val green_500 = getColor(R.color.green_500)
    @ColorInt val green_600 = getColor(R.color.green_600)
    @ColorInt val green_700 = getColor(R.color.green_700)
    @ColorInt val green_800 = getColor(R.color.green_800)
    @ColorInt val green_900 = getColor(R.color.green_900)
    @ColorInt val green_a100 = getColor(R.color.green_a100)
    @ColorInt val green_a200 = getColor(R.color.green_a200)
    @ColorInt val green_a400 = getColor(R.color.green_a400)
    @ColorInt val green_a700 = getColor(R.color.green_a700)

    @ColorInt val light_green_50 = getColor(R.color.light_green_50)
    @ColorInt val light_green_100 = getColor(R.color.light_green_100)
    @ColorInt val light_green_200 = getColor(R.color.light_green_200)
    @ColorInt val light_green_300 = getColor(R.color.light_green_300)
    @ColorInt val light_green_400 = getColor(R.color.light_green_400)
    @ColorInt val light_green_500 = getColor(R.color.light_green_500)
    @ColorInt val light_green_600 = getColor(R.color.light_green_600)
    @ColorInt val light_green_700 = getColor(R.color.light_green_700)
    @ColorInt val light_green_800 = getColor(R.color.light_green_800)
    @ColorInt val light_green_900 = getColor(R.color.light_green_900)
    @ColorInt val light_green_a100 = getColor(R.color.light_green_a100)
    @ColorInt val light_green_a200 = getColor(R.color.light_green_a200)
    @ColorInt val light_green_a400 = getColor(R.color.light_green_a400)
    @ColorInt val light_green_a700 = getColor(R.color.light_green_a700)

    @ColorInt val lime_50 = getColor(R.color.lime_50)
    @ColorInt val lime_100 = getColor(R.color.lime_100)
    @ColorInt val lime_200 = getColor(R.color.lime_200)
    @ColorInt val lime_300 = getColor(R.color.lime_300)
    @ColorInt val lime_400 = getColor(R.color.lime_400)
    @ColorInt val lime_500 = getColor(R.color.lime_500)
    @ColorInt val lime_600 = getColor(R.color.lime_600)
    @ColorInt val lime_700 = getColor(R.color.lime_700)
    @ColorInt val lime_800 = getColor(R.color.lime_800)
    @ColorInt val lime_900 = getColor(R.color.lime_900)
    @ColorInt val lime_a100 = getColor(R.color.lime_a100)
    @ColorInt val lime_a200 = getColor(R.color.lime_a200)
    @ColorInt val lime_a400 = getColor(R.color.lime_a400)
    @ColorInt val lime_a700 = getColor(R.color.lime_a700)

    @ColorInt val yellow_50 = getColor(R.color.yellow_50)
    @ColorInt val yellow_100 = getColor(R.color.yellow_100)
    @ColorInt val yellow_200 = getColor(R.color.yellow_200)
    @ColorInt val yellow_300 = getColor(R.color.yellow_300)
    @ColorInt val yellow_400 = getColor(R.color.yellow_400)
    @ColorInt val yellow_500 = getColor(R.color.yellow_500)
    @ColorInt val yellow_600 = getColor(R.color.yellow_600)
    @ColorInt val yellow_700 = getColor(R.color.yellow_700)
    @ColorInt val yellow_800 = getColor(R.color.yellow_800)
    @ColorInt val yellow_900 = getColor(R.color.yellow_900)
    @ColorInt val yellow_a100 = getColor(R.color.yellow_a100)
    @ColorInt val yellow_a200 = getColor(R.color.yellow_a200)
    @ColorInt val yellow_a400 = getColor(R.color.yellow_a400)
    @ColorInt val yellow_a700 = getColor(R.color.yellow_a700)

    @ColorInt val amber_50 = getColor(R.color.amber_50)
    @ColorInt val amber_100 = getColor(R.color.amber_100)
    @ColorInt val amber_200 = getColor(R.color.amber_200)
    @ColorInt val amber_300 = getColor(R.color.amber_300)
    @ColorInt val amber_400 = getColor(R.color.amber_400)
    @ColorInt val amber_500 = getColor(R.color.amber_500)
    @ColorInt val amber_600 = getColor(R.color.amber_600)
    @ColorInt val amber_700 = getColor(R.color.amber_700)
    @ColorInt val amber_800 = getColor(R.color.amber_800)
    @ColorInt val amber_900 = getColor(R.color.amber_900)
    @ColorInt val amber_a100 = getColor(R.color.amber_a100)
    @ColorInt val amber_a200 = getColor(R.color.amber_a200)
    @ColorInt val amber_a400 = getColor(R.color.amber_a400)
    @ColorInt val amber_a700 = getColor(R.color.amber_a700)

    @ColorInt val orange_50 = getColor(R.color.orange_50)
    @ColorInt val orange_100 = getColor(R.color.orange_100)
    @ColorInt val orange_200 = getColor(R.color.orange_200)
    @ColorInt val orange_300 = getColor(R.color.orange_300)
    @ColorInt val orange_400 = getColor(R.color.orange_400)
    @ColorInt val orange_500 = getColor(R.color.orange_500)
    @ColorInt val orange_600 = getColor(R.color.orange_600)
    @ColorInt val orange_700 = getColor(R.color.orange_700)
    @ColorInt val orange_800 = getColor(R.color.orange_800)
    @ColorInt val orange_900 = getColor(R.color.orange_900)
    @ColorInt val orange_a100 = getColor(R.color.orange_a100)
    @ColorInt val orange_a200 = getColor(R.color.orange_a200)
    @ColorInt val orange_a400 = getColor(R.color.orange_a400)
    @ColorInt val orange_a700 = getColor(R.color.orange_a700)

    @ColorInt val deep_orange_50 = getColor(R.color.deep_orange_50)
    @ColorInt val deep_orange_100 = getColor(R.color.deep_orange_100)
    @ColorInt val deep_orange_200 = getColor(R.color.deep_orange_200)
    @ColorInt val deep_orange_300 = getColor(R.color.deep_orange_300)
    @ColorInt val deep_orange_400 = getColor(R.color.deep_orange_400)
    @ColorInt val deep_orange_500 = getColor(R.color.deep_orange_500)
    @ColorInt val deep_orange_600 = getColor(R.color.deep_orange_600)
    @ColorInt val deep_orange_700 = getColor(R.color.deep_orange_700)
    @ColorInt val deep_orange_800 = getColor(R.color.deep_orange_800)
    @ColorInt val deep_orange_900 = getColor(R.color.deep_orange_900)
    @ColorInt val deep_orange_a100 = getColor(R.color.deep_orange_a100)
    @ColorInt val deep_orange_a200 = getColor(R.color.deep_orange_a200)
    @ColorInt val deep_orange_a400 = getColor(R.color.deep_orange_a400)
    @ColorInt val deep_orange_a700 = getColor(R.color.deep_orange_a700)

    @ColorInt val brown_50 = getColor(R.color.brown_50)
    @ColorInt val brown_100 = getColor(R.color.brown_100)
    @ColorInt val brown_200 = getColor(R.color.brown_200)
    @ColorInt val brown_300 = getColor(R.color.brown_300)
    @ColorInt val brown_400 = getColor(R.color.brown_400)
    @ColorInt val brown_500 = getColor(R.color.brown_500)
    @ColorInt val brown_600 = getColor(R.color.brown_600)
    @ColorInt val brown_700 = getColor(R.color.brown_700)
    @ColorInt val brown_800 = getColor(R.color.brown_800)
    @ColorInt val brown_900 = getColor(R.color.brown_900)

    @ColorInt val blue_gray_50 = getColor(R.color.blue_gray_50)
    @ColorInt val blue_gray_100 = getColor(R.color.blue_gray_100)
    @ColorInt val blue_gray_200 = getColor(R.color.blue_gray_200)
    @ColorInt val blue_gray_300 = getColor(R.color.blue_gray_300)
    @ColorInt val blue_gray_400 = getColor(R.color.blue_gray_400)
    @ColorInt val blue_gray_500 = getColor(R.color.blue_gray_500)
    @ColorInt val blue_gray_600 = getColor(R.color.blue_gray_600)
    @ColorInt val blue_gray_700 = getColor(R.color.blue_gray_700)
    @ColorInt val blue_gray_800 = getColor(R.color.blue_gray_800)
    @ColorInt val blue_gray_900 = getColor(R.color.blue_gray_900)

    @ColorInt val black = getColor(R.color.black)
    @ColorInt val white = getColor(R.color.white)
}